import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";

const Home = () => {
  return (
    <>
      <Head>
        <title>BHSS Coffee Shop Ordering App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-full min-h-screen flex-col items-center justify-center gap-4">
        <Link href="/order">
          <button className="rounded border border-blue-500 bg-transparent px-4 py-2 font-semibold text-blue-700 hover:border-transparent hover:bg-blue-500 hover:text-white">
            Place An Order
          </button>
        </Link>
        <Link href="/counter">
          <button className="rounded border border-blue-500 bg-transparent px-4 py-2 font-semibold text-blue-700 hover:border-transparent hover:bg-blue-500 hover:text-white">
            View Current Orders
          </button>
        </Link>
      </main>
    </>
  );
};

export default Home;
